inherit_gem:
  google-style: google-style.yml

AllCops:
  Exclude:
    - "google-gax.gemspec"
    - "test/**/*"

Style/Documentation:
  Exclude:
    - "lib/google/gax/api_call.rb"
    - "lib/google/gax/settings.rb"
    - "lib/google/gax/errors.rb"
Style/GuardClause:
  Exclude:
    - "lib/google/gax/grpc/stub.rb"
