inherit_from: .rubocop_todo.yml

# Prefer compact style, as Ruby runtime overwrites the GAX error message
# when exploded exception style is used.
Metrics/ClassLength:
  Max: 110
Style/RaiseArgs:
  EnforcedStyle: compact

Metrics/ParameterLists:
  Exclude:
    - 'lib/google/gax/api_call.rb'
    - 'lib/google/gax/grpc.rb'
